### ISSUE TITLE
Improve the LRISb 300/5000 solution

### ISSUE THREAD

**Issue by profxj** [PYPIT/arclines#22]
For @AlexaVillaume (and others).

Work in progress:

arclines_match lrisb_300_5000_PYPIT.json 4500. 1.43 HgI,NeI,CdI,ZnI,ArI --fit --min_ampl=20 --ylog --debug

**Comment by profxj** [comment]
Am working in lrisb_300_5000 branch

**Comment by profxj** [comment]
@AlexaVillaume -- are you happy with where you got
as regards arclines?  If so, kindly close this Issue

**Comment by AlexaVillaume** [comment]
I think so. The updates Ryan made seem to have helped a lot.
